title:              Nick Byrne
email:              nick@typehuman.com
description:        A collection of thoughts about technology & innovation
author:             Nick Byrne
baseurl:            "/"
url:                "https://nickbyrne.blog"

# Social Profiles
twitter_username:   byrnenick
github_username:    byrnenick 
facebook_username:  
linkedin_username:  nbyrne

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-150420454-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-compress-images
